### ISSUE TITLE
Prepare for repo migration under azure org repo 

### ISSUE THREAD

**Issue by manekinekko** [Azure/static-web-apps-cli#39]
**TODO**

- [x] rename npm package to `@azure/static-web-apps-cli`
- [x] update the readme and rename SWA EMU to  `Static Web Apps CLI` or `SWA CLI`.
- [x] change license authors
- [x] change authors in package.json
- [x] delete `AFFILIATION_NOTICE.md`
- [x] update `CODE_OF_CONDUCT.md`
- [x] replace all `https://github.com/manekinekko/swa-emulator/` references with the new repo url
- [x] add repo files requires by Microsoft OSPO (`SECURITY.md`, ...)
- [x] rename repo to `static-web-apps-cli` (Blocked by https://github.com/Azure/static-web-apps-cli/issues/1)
- [ ] update the release-it config (Blocked by https://github.com/Azure/swa-emulator/issues/51)

CC @anthonychu please add any other items to this checklist.
